def nps_parks_root():
 return ['Abraham Lincoln Park',
 'Acadia',
 'Adams Park',
 'African American War Memorial',
 'African Burial Ground',
 'Agate Fossil Beds',
 'Ala Kahakai Trail',
 'Alagnak',
 'Alaska',
 'Alcatraz Island',
 'Aleutian Islands',
 'Alibates',
 'Allegheny',
 'Amache',
 'American Memorial',
 'Amistad',
 'Anacostia',
 'Andersonville',
 'Andrew Johnson',
 'Aniakchak',
 'Antietam',
 'Apostle',
 'Appalachian',
 'Appomattox',
 'Arches',
 'Arkansas Post',
 'Arlington House',
 'Assateague',
 'Aztec',
 'Badlands',
 'Baltimore-Washington',
 'Bandelier',
 "Belmont-Paul",
 "Bent's Old Fort",
 'Bering Land',
 'Big Bend',
 'Big Cypress',
 'Big Hole',
 'Big South Fork',
 'Big Thicket',
 'Bighorn Canyon',
 'Birmingham',
 'Biscayne',
 'Black Canyon',
 'Blackstone River',
 'Blackwell',
 'Blue Ridge',
 'Bluestone',
 'Booker T Washington',
 'Boston African American',
 'Boston Harbor Islands',
 'Boston',
 'Brices Cross Roads',
 'Brown v. Board of Education',
 'Bryce Canyon',
 'Buck Island',
 'Buffalo',
 'Butterfield Overland',
 'Cabrillo',
 'California Trail',
 'Camp Nelson',
 'Canaveral',
 'Cane River',
 'Canyon de Chelly',
 'Canyonlands',
 'Cape Cod',
 'Cape Hatteras',
 'Cape Henry',
 'Cape Krusenstern',
 'Cape Lookout',
 'Capitol Hill',
 'Capitol Reef',
 'John Smith',
 'Capulin Volcano',
 'Carl Sandburg',
 'Carlsbad',
 'Carter G. Woodson',
 'Casa Grande Ruins',
 'Castillo de San Marcos',
 'Castle Clinton',
 'Castle Mountains',
 'Catoctin Mountain Park',
 'Cedar Breaks',
 'Cedar Creek & Belle Grove',
 'Chaco Culture',
 'Chamizal',
 'Channel Islands',
 'Charles Pinckney',
 'Charles Young Buffalo Soldiers',
 'Chattahoochee River',
 'Chesapeake & Ohio Canal',
 'Chesapeake Bay',
 'Chickamauga & Chattanooga',
 'Chickasaw',
 'Chiricahua',
 'Christiansted',
 'City Of Rocks',
 'Civil War Defenses of Washington',
 'Clara Barton',
 'Colonial',
 'Colorado',
 'Coltsville',
 'Congaree',
 'Constitution Gardens',
 'Coronado',
 'Cowpens',
 'Crater Lake',
 'Craters Of The Moon',
 'Cumberland Gap',
 'Cumberland Island',
 'Curecanti',
 'Cuyahoga Valley',
 'César E. Chávez',
 'Dayton Aviation Heritage',
 'De Soto',
 'Death Valley',
 'Delaware Water Gap',
 'Denali',
 'Devils Postpile',
 'Devils Tower',
 'Dinosaur',
 'Dry Tortugas',
 'Dwight D. Eisenhower Memorial',
 "Ebey's Landing",
 'Edgar Allan Poe',
 'Effigy Mounds',
 'Eisenhower',
 'El Camino Real de Tierra Adentro',
 'El Camino Real de los Tejas',
 'El Malpais',
 'El Morro',
 'Eleanor Roosevelt',
 'Ellis Island',
 'Emmett Till',
 "Eugene O'Neill",
 'Everglades',
 'Federal Hall',
 'Fire Island',
 'First Ladies',
 'First State',
 'Flight 93',
 'Florissant Fossil Beds',
 "Ford's Theatre",
 'Fort Bowie',
 'Fort Davis',
 'Fort Donelson',
 'Fort Dupont Park',
 'Fort Foote Park',
 'Fort Frederica',
 'Fort Laramie',
 'Fort Larned',
 'Fort Matanzas',
 'Fort McHenry',
 'Fort Monroe',
 'Fort Necessity',
 'Fort Point',
 'Fort Pulaski',
 'Fort Raleigh',
 'Fort Scott',
 'Fort Smith',
 'Fort Stanwix',
 'Fort Sumter and Fort Moultrie',
 'Fort Union Monument',
 'Fort Union Trading Post',
 'Fort Vancouver',
 'Fort Washington Park',
 'Fossil Butte',
 'Franklin Delano Roosevelt Memorial',
 'Frederick Douglass',
 'Frederick Law Olmsted',
 'Fredericksburg',
 'Freedom Riders',
 'Friendship Hill',
 'Gates Of The Arctic',
 'Gateway Arch',
 'Gateway',
 'Gauley River',
 'General Grant',
 'George Rogers Clark',
 'George Washington Birthplace',
 'George Washington Carver',
 'George Washington Memorial Parkway',
 'Gettysburg',
 'Gila Cliff Dwellings',
 'Glacier Bay',
 'Glacier',
 'Glen Canyon',
 'Glen Echo Park',
 'Gloria Dei Church',
 'Golden Gate',
 'Golden Spike',
 'Governors Island',
 'Grand Canyon',
 'Grand Canyon-Parashant',
 'Grand Portage',
 'Grand Teton',
 'Grant-Kohrs Ranch',
 'Great Basin',
 'Great Egg Harbor River',
 'Great Falls Park',
 'Great Sand Dunes',
 'Smoky Mountains',
 'Green Springs',
 'Greenbelt Park',
 'Guadalupe Mountains',
 'Guilford Courthouse',
 'Gulf Islands',
 'Hagerman Fossil Beds',
 'Haleakalā',
 'Hamilton Grange',
 'Hampton',
 'Harmony Hall',
 'Harpers Ferry',
 'Harriet Tubman',
 'Harriet Tubman Underground Railroad',
 'Harry S Truman',
 'Hawaiʻi Volcanoes',
 'Herbert Hoover',
 'Jamestowne',
 'Franklin D Roosevelt Home',
 'Homestead',
 'Honouliuli',
 'Hopewell Culture',
 'Hopewell Furnace',
 'Horseshoe Bend',
 'Hot Springs',
 'Hovenweep',
 'Hubbell Trading Post',
 'Ice Age Floods',
 'Ice Age',
 'Independence',
 'Indiana Dunes',
 'Isle Royale',
 'Iñupiat Heritage Center',
 'James A Garfield',
 'Jean Lafitte',
 'Jewel Cave',
 'Jimmy Carter',
 'John Day Fossil Beds',
 'John Fitzgerald Kennedy',
 'John Muir',
 'Johnstown Flood',
 'Joshua Tree',
 'Juan Bautista de Anza',
 'Kalaupapa',
 'Kaloko-Honokōhau',
 'Katahdin Woods and Waters',
 'Katmai',
 'Kenai Fjords',
 'Kenilworth Park & Aquatic Gardens',
 'Kennesaw Mountain Park',
 'Keweenaw',
 'Kings Mountain',
 'Klondike Gold Rush Seattle',
 'Klondike Gold Rush',
 'Knife River Indian Villages',
 'Kobuk Valley',
 'Korean War Veterans Memorial',
 'LBJ Memorial',
 'Lake Clark',
 'Lake Mead',
 'Lake Meredith',
 'Lake Roosevelt',
 'Lassen Volcanic',
 'Lava Beds',
 'Lewis & Clark Trail',
 'Lewis and Clark Park',
 'Lincoln Boyhood',
 'Lincoln Home',
 'Lincoln Memorial',
 'Little Bighorn Battlefield',
 'Little River Canyon',
 'Little Rock Central High School',
 "Longfellow House Washington's Headquarters",
 'Lowell',
 'Lower Delaware',
 'Lower East Side Tenement Museum',
 'Lyndon B Johnson',
 'Maggie L Walker',
 'Maine Acadian Culture',
 'Mammoth Caves',
 'Manassas Park',
 'Manhattan Project',
 'Manzanar',
 'Marsh - Billings - Rockefeller',
 'Martin Luther King, Jr. Memorial',
 'Martin Luther King, Jr.',
 'Martin Van Buren',
 'Mary McLeod Bethune Council House',
 'Medgar and Myrlie Evers Home',
 'Mesa Verde',
 'Mill Springs Battlefield',
 'Minidoka',
 'Minute Man',
 'Minuteman Missile',
 'Mississippi River',
 'Missouri National Recreational River',
 'Mojave National Preserve',
 'Monocacy',
 'Montezuma Castle',
 'Moores Creek',
 'Mormon Pioneer',
 'Morristown',
 'Mount Rainier',
 'Mount Rushmore',
 'Muir Woods',
 'Natchez',
 'Natchez Trace Trail',
 'Natchez Trace Parkway',
 'National Capital Parks-East',
 'National Mall and Memorial Parks',
 'National Park of American Samoa',
 'National Parks of New York Harbor',
 'Natural Bridges',
 'Navajo',
 'New Bedford Whaling',
 'New England Trail',
 'New Jersey Pinelands',
 'New Orleans Jazz',
 'New Philadelphia',
 'New River Gorge',
 'Nez Perce',
 'Nicodemus',
 'Ninety Six',
 'Niobrara',
 'Noatak',
 'North Cascades',
 'North Country',
 'Obed Wild & Scenic River',
 'Ocmulgee Mounds',
 'Oklahoma City',
 'Old Spanish',
 'Olympic',
 'Oregon Caves',
 'Oregon',
 'Organ Pipe Cactus',
 'Overmountain Victory',
 'Oxon Cove Park & Oxon Hill Farm',
 'Ozark',
 'Padre Island',
 'Palo Alto Battlefield',
 'Paterson Great Falls',
 'Pea Ridge',
 'Pearl Harbor',
 'Pecos',
 'Pennsylvania Avenue',
 "Perry's Victory & International Peace Memorial",
 'Petersburg',
 'Petrified Forest',
 'Petroglyph',
 'Pictured Rocks',
 'Pinnacles',
 'Pipe Spring',
 'Pipestone',
 'Piscataway Park',
 'Point Reyes',
 'Pony Express',
 'Port Chicago Naval Magazine',
 'Potomac Heritage',
 'Poverty Point',
 'William Jefferson Home',
 'Presidio of San Francisco',
 'Prince William Forest Park',
 'Pullman',
 'Puʻuhonua o Hōnaunau',
 'Puʻukoholā Heiau',
 'Rainbow Bridge',
 'Reconstruction Era',
 'Redwood',
 'Richmond Park',
 'Rio Grande Wild & Scenic River',
 'River Raisin Park',
 'Rock Creek Park',
 'Rocky Mountain',
 'Roger Williams',
 'Roosevelt Campobello',
 'Rosie the Riveter WWII Home Front',
 'Russell Cave',
 'Sagamore Hill',
 'Saguaro',
 'Saint Croix Island',
 'Saint Croix Riverway',
 "Saint Paul's Church",
 'Saint-Gaudens',
 'Salem Maritime',
 'Salinas Pueblo Missions',
 'Salt River Bay',
 'San Antonio Missions',
 'San Francisco Maritime',
 'San Juan Island',
 'San Juan',
 'Sand Creek Massacre',
 'Santa Fe',
 'Santa Monica Mountains',
 'Saratoga',
 'Saugus Iron Works',
 'Scotts Bluff',
 'Selma To Montgomery',
 'Sequoia',
 'Shenandoah',
 'Shiloh',
 'Sitka',
 'Sleeping Bear Dunes',
 'Springfield Armory',
 'Star-Spangled Banner',
 'Statue Of Liberty',
 'Ste. Geneviève',
 'Steamtown',
 'Stones River',
 'Stonewall',
 'Sunset Crater Volcano',
 'Tallgrass Prairie',
 'Thaddeus Kosciuszko',
 "The White House Park",
 'Theodore Roosevelt Birthplace',
 'Theodore Roosevelt Inaugural',
 'Theodore Roosevelt Island',
 'Theodore Roosevelt',
 'Thomas Cole',
 'Thomas Edison',
 'Thomas Jefferson',
 'Thomas Stone',
 'Timpanogos',
 'Timucuan',
 'Tonto',
 'Touro Synagogue',
 'Trail Of Tears',
 'Tule Lake',
 'Tule Springs Fossil',
 'Tumacácori',
 'Tupelo',
 'Tuskegee Airmen',
 'Tuskegee Institute',
 'Tuzigoot',
 'Ulysses S Grant',
 'Upper Delaware',
 'Valles Caldera',
 'Valley Forge',
 'Vanderbilt',
 'Vicksburg',
 'Vietnam Veterans',
 'Virgin Islands Coral Reef',
 'Virgin Islands',
 'Voyageurs',
 'Waco Mammoth',
 'Walnut Canyon',
 'War In The Pacific',
 'Washington Monument',
 'Washington-Rochambeau',
 'Washita',
 'Weir Farm',
 'Whiskeytown',
 'White Sands',
 'Whitman Mission',
 'William Howard Taft',
 "Wilson's Creek",
 'Wind Cave',
 'Wing Luke',
 'Wolf Trap',
 "Women's Rights",
 'World War I Memorial',
 'World War II Memorial',
 'Wrangell',
 'Wright Brothers',
 'Wupatki',
 'Yellowstone',
 'Yorktown',
 'Yosemite',
 'Yucca House',
 'Yukon',
 'Zion']